server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///lhq_admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.gxuwz.admin: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
